controllers/AuthenticationController.php
<?php
namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\logic\UserManager;
use app\models\RegistrationForm;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\db\Exception;



class AuthenticationController extends Controller{
    private $loginForm;
    private $registrationForm;
    
    function __construct($id, $module){
        parent::__construct($id, $module);
        $this->loginForm = new LoginForm();
        $this->registrationForm = new RegistrationForm();
     }
     
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }
     
    public function actionLogin() {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        if (Yii::$app->request->isAjax && $this->loginForm->load(Yii::$app->request->post())) {
              if($this->loginForm->validate()){
                $manager = new UserManager();
                if($manager->Login($this->loginForm)){ $this->goHome();}
                else{  
                    $this->loginForm->addError("login","User with such password and username does not exist.");
                    return $this->render('//site/login',["model"=>$this->loginForm]);  
                 }
              }
              else{ return $this->render('//site/login',["model"=>$this->loginForm]); }
        } 
        else{ $this->render('//site/login',["model"=>$this->loginForm]); }
    }
 
    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->goHome();
    }
    
    public function actionRegistration(){
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        if (Yii::$app->request->isAjax && $this->registrationForm->load(Yii::$app->request->post())) {
          if($this->registrationForm->validate()){
                $manager = new UserManager();
                try{
                    $manager->Registration($this->registrationForm->login, $this->registrationForm->password);
                    $this->loginForm->login = $this->registrationForm->login;
                    $this->loginForm->password = $this->registrationForm->password;
                    $this->loginForm->rememberMe = false;
                    $manager->Login($this->loginForm);
                    return $this->goHome();
                }
                catch(Exception $ex){
                    $this->registrationForm->addError("login","A user with this login already exists. Try another.");
                    return $this->render('//site/registration',['model'=>$this->registrationForm]);
                }   
            }
            else{ return $this->render('//site/registration',['model'=>$this->registrationForm]); }   
        }
        else{ return $this->render('//site/registration',['model'=>$this->registrationForm]); }
        
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Book;
use yii\data\ActiveDataProvider;
use app\models\Author;
use app\models\BookFilterForm;
use app\models\NewBookForm;
use app\models\RegistrationForm;
use app\models\LoginForm;
use yii\data\Pagination;
use app\models\Category;
use app\models\AddCategoryForm;
use app\models\AddAuthorForm;


class SiteController extends Controller{ 
    
    private $books;
    private $bookPages;
    private $addBookModel;
    private $selectedCategory;
    private $addCategoryModel;
    private $addAuthorModel;


    public function actions(){
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    
    function __construct($id, $module){
        parent::__construct($id, $module);
        $model = Book::find()
                ->with('authors')
                ->with('categories');
        $countQuery = clone $model;
        $this->bookPages = new Pagination(['totalCount' => $countQuery->count(),'pageSize'=>9]);
        $this->books = $model->offset($this->bookPages->offset)
                 ->limit($this->bookPages->limit)
                 ->all();
        $this->addBookModel = new NewBookForm();
        $this->selectedCategory = "book";
        $this->addCategoryModel = new AddCategoryForm();
        $this->addAuthorModel = new AddAuthorForm(); 
     }

    public function actionIndex(){
        return $this->render('index',[
            "books"=>$this->books,
            "bookPages" => $this->bookPages,
            "addBookModel" => $this->addBookModel,
            "selectedCategory"=> $this->selectedCategory,
            "addCategoryModel" => $this->addCategoryModel,
            "addAuthorModel"=> $this->addAuthorModel
            ]);
    }

    public function actionAbout() {
        return $this->render('about');
    }
    
    public function actionLogin(){
        return $this->render('login',['model'=>new LoginForm()]);
     }
     
    public function actionRegistration(){
        return $this->render('registration',['model'=> new RegistrationForm()]);
     }  
}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\models\LoginForm;
use app\models\RegistrationForm;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <link href="assets/content/images/logo.png" rel="icon">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
   <?php
    NavBar::begin([
        'brandLabel' => Html::img('assets/content/images/logo.png'),
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top navbar-default',
            'id' => 'main-menu'
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-left navbar-default'],
        'items' => [
            ['label' => 'Library', 'url' => ['/site/index']],
        ],
    ]);
    $menuItems = [];
    if(Yii::$app->user->isGuest){
        $menuItems[] = ['label' => 'Login','url' => ['/site/login']];
        $menuItems[] = ['label' => 'Registration','url' => ['/site/registration']]; 
    }
    else{
        $menuItems[] = [
            'label' => 'Add',
            'items' => [
                 ['label' => 'Add book',
                  "options" =>["id"=>"add-book-btn"],
                  'url' => '#'   ],
                ['label' => 'Add category',
                  "options" =>["id"=>"add-category-btn"],
                  'url' => '#'   ],
                ['label' => 'Add author',
                  "options" =>["id"=>"add-author-btn"],
                  'url' => '#'   ],
            ],
            ];
        $menuItems[] = ['label' => 'LogOut', 'url' => ['/authentication/logout']];  
    }
    
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems
    ]);  
    
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>