controllers/AuthorController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Book;
use app\models\Author;
use app\models\BookFilterForm;
use app\models\NewBookForm;
use app\models\RegistrationForm;
use app\models\LoginForm;
use yii\data\Pagination;
use app\models\AddCategoryForm;
use app\models\AddAuthorForm;


class AuthorController extends Controller{ 
    
    public function actions(){
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    
    private $books;
    private $bookPages;
    private $addBookModel;
    private $selectedCategory;
    private $addCategoryModel;
    private $addAuthorModel;
            
    function __construct($id, $module){
        parent::__construct($id, $module);
        $this->Initialization();
     }
     
    public function Initialization(){
        $model = Book::find()
                ->with('authors')
                ->with('categories');
        $countQuery = clone $model;
        $this->bookPages = new Pagination(['totalCount' => $countQuery->count(),'pageSize'=>3]);
        $this->books = $model->offset($this->bookPages->offset)
                 ->limit($this->bookPages->limit)
                 ->all();
       $this->addBookModel = new NewBookForm();
       $this->selectedCategory = "author";
       $this->addCategoryModel = new AddCategoryForm();
       $this->addAuthorModel = new AddAuthorForm();     
     }

    public function actionIndex(){
        return $this->render('//site/index',[
            "books"=>$this->books,
            "bookPages" => $this->bookPages,
            "addBookModel" => $this->addBookModel,
            "selectedCategory"=> $this->selectedCategory,
            "addCategoryModel" => $this->addCategoryModel,
            "addAuthorModel"=> $this->addAuthorModel
            ]);
    } 
     
    public function actionSelect(){
         $id = Yii::$app->getRequest()->getQueryParam('id');
         $model = Book::find()
                ->where(["author.author_id"=>$id])
                ->innerJoinWith('authors')
                ->with('authors')
                ->with('categories');
        $countQuery = clone $model;
        $this->bookPages = new Pagination(['totalCount' => $countQuery->count(),'pageSize'=>6]);
        $this->books = $model->offset($this->bookPages->offset)
                 ->limit($this->bookPages->limit)
                 ->all();
        return $this->render('//site/index',[
                    "books"=>$this->books,
                    "bookPages" => $this->bookPages,
                    "addBookModel" => $this->addBookModel,
                    "selectedCategory"=> $this->selectedCategory
                    ]);
    }
    
    public function actionAdd(){
          if ($this->addAuthorModel->load(Yii::$app->request->post())){
               if($this->addAuthorModel->validate()){
                  $author = new Author(); 
                  $author->first_name = $this->addAuthorModel->first_name;
                  $author->second_name = $this->addAuthorModel->second_name;
                  try{
                     $author->save(); 
                     $this->Initialization();
                     return $this->refresh();
                  }
                   catch (\yii\db\Exception $ex){
                       $this->addAuthorModel->addError("name","This author is already exist.");
                       return $this->actionIndex();
                   }
                   
               }
               return $this->actionIndex();
          }
          return $this->actionIndex();
    }
  
}

controllers/CategoryController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Book;
use yii\data\ActiveDataProvider;
use app\models\Author;
use app\models\BookFilterForm;
use app\models\NewBookForm;
use app\models\RegistrationForm;
use app\models\LoginForm;
use yii\data\Pagination;
use app\models\SelectCategory;
use app\models\AddCategoryForm;
use app\models\Category;
use app\models\AddAuthorForm;


class CategoryController extends Controller{ 
    
    public function actions(){
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    
    private $books;
    private $bookPages;
    private $addBookModel;
    private $selectedCategory;
    private $addCategoryModel;
    private $addAuthorModel;
            
    function __construct($id, $module){
        parent::__construct($id, $module);
        $this->Initialization();   
     }
    
    public function actionIndex(){
        return $this->render('//site/index',[
            "books"=>$this->books,
            "bookPages" => $this->bookPages,
            "addBookModel" => $this->addBookModel,
            "selectedCategory"=> $this->selectedCategory,
            "addCategoryModel" => $this->addCategoryModel,
            "addAuthorModel"=> $this->addAuthorModel
            ]);
    } 
    
    public function Initialization(){
        $model = Book::find()
                ->with('authors')
                ->with('categories');
        $countQuery = clone $model;
        $this->bookPages = new Pagination(['totalCount' => $countQuery->count(),'pageSize'=>3]);
        $this->books = $model->offset($this->bookPages->offset)
                 ->limit($this->bookPages->limit)
                 ->all();
        $this->addBookModel = new NewBookForm();
        $this->selectedCategory = "category";
        $this->addCategoryModel = new AddCategoryForm();
        $this->addAuthorModel = new AddAuthorForm();    
    }

    public function actionAdd(){
          if ($this->addCategoryModel->load(Yii::$app->request->post())){
               if($this->addCategoryModel->validate()){
                  $category = new Category(); 
                  $category->name = $this->addCategoryModel->name;
                  try{
                     $category->save();
                     $this->Initialization();
                     return $this->refresh();
                  }
                   catch (\yii\db\Exception $ex){
                       $this->addCategoryModel->addError("name","That category is already exist.");
                       return $this->actionIndex();
                   }
                   
               }
               return $this->actionIndex();
          }
          return $this->actionIndex();
    }
    
    public function actionSelect(){
         $id = Yii::$app->getRequest()->getQueryParam('id');
         $model = Book::find()
                ->where(["category.category_id"=>$id])
                ->innerJoinWith('categories')
                ->with('authors')
                ->with('categories');
        $countQuery = clone $model;
        $this->bookPages = new Pagination(['totalCount' => $countQuery->count(),'pageSize'=>6]);
        $this->books = $model->offset($this->bookPages->offset)
                 ->limit($this->bookPages->limit)
                 ->all();
        return $this->render('//site/index',[
                    "books"=>$this->books,
                    "bookPages" => $this->bookPages,
                    "addBookModel" => $this->addBookModel,
                    "selectedCategory"=> $this->selectedCategory,
                    "addCategoryModel" => $this->addCategoryModel
                    ]);
    }
    
   
  
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Book;
use yii\data\ActiveDataProvider;
use app\models\Author;
use app\models\BookFilterForm;
use app\models\NewBookForm;
use app\models\RegistrationForm;
use app\models\LoginForm;
use yii\data\Pagination;
use app\models\Category;
use app\models\AddCategoryForm;
use app\models\AddAuthorForm;


class SiteController extends Controller{ 
    
    private $books;
    private $bookPages;
    private $addBookModel;
    private $selectedCategory;
    private $addCategoryModel;
    private $addAuthorModel;


    public function actions(){
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    
    function __construct($id, $module){
        parent::__construct($id, $module);
        $model = Book::find()
                ->with('authors')
                ->with('categories');
        $countQuery = clone $model;
        $this->bookPages = new Pagination(['totalCount' => $countQuery->count(),'pageSize'=>9]);
        $this->books = $model->offset($this->bookPages->offset)
                 ->limit($this->bookPages->limit)
                 ->all();
        $this->addBookModel = new NewBookForm();
        $this->selectedCategory = "book";
        $this->addCategoryModel = new AddCategoryForm();
        $this->addAuthorModel = new AddAuthorForm(); 
     }

    public function actionIndex(){
        return $this->render('index',[
            "books"=>$this->books,
            "bookPages" => $this->bookPages,
            "addBookModel" => $this->addBookModel,
            "selectedCategory"=> $this->selectedCategory,
            "addCategoryModel" => $this->addCategoryModel,
            "addAuthorModel"=> $this->addAuthorModel
            ]);
    }

    public function actionAbout() {
        return $this->render('about');
    }
    
    public function actionLogin(){
        return $this->render('login',['model'=>new LoginForm()]);
     }
     
    public function actionRegistration(){
        return $this->render('registration',['model'=> new RegistrationForm()]);
     }  
}

views/site/Registration.php
<?php
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
?>
<div class="container">
    <div class="col-md-offset-4 col-md-4 center-form">
        <div class="panel panel-default">
            <div class="panel-body">
              Registration
            </div>
            <div class="panel-footer">
                 <?php Pjax::begin(['timeout' => 5000]); ?>
                 <?php $form = ActiveForm::begin([
                             'id' => 'login-form',
                             'method' => 'post',
                             'action' => ['authentication/registration'],
                             'options' => ['onsubmit' => 'return false','data-pjax' => true],
                             'enableClientValidation' => true,
                              ]); ?>
            
                  <div class="form-group">
                       <?= $form->field($model, 'login')->label("Login") ?>
                  </div>


                  <div class="form-group">
                       <?= $form->field($model, 'password')->passwordInput()->label("Password") ?>
                  </div>
                
                  <div class="form-group">
                       <?= $form->field($model, 'confirmPassword')->passwordInput()->label("ConfirmPassword") ?>
                  </div>
                
                  <div class="modal-footer">
                      <button type="submit" class="btn btn-primary" id="login-btn">Registrtion</button>
                      <button type="reset" class="btn btn-default" data-dismiss="modal">Clear</button>
                  </div>
        
                 <?php ActiveForm::end(); ?>
              <?php Pjax::end(); ?>
            </div>
          </div>
    </div>
</div>
            
           

views/site/_authorReview.php
<?php 
use app\models\Author;
use yii\helpers\Html;

$authors = Author::find()->andWhere(['>','author_id',0])->all();
?>
<div class="col-md-4">
    <div class="list-group">
        <?php
          foreach ($authors as $author){
              if(isset($_GET['id'])){
                  if($author->author_id == $_GET['id']){
                        echo Html::a($author->first_name. " ".$author->second_name,['author/select', 'id' =>$author->author_id],["class"=>"list-group-item active"] );   
                  }
                  else{
                        echo Html::a($author->first_name. " ".$author->second_name,['author/select', 'id' =>$author->author_id],["class"=>"list-group-item"] );  
                  } 
              }
              else{
                  echo Html::a($author->first_name. " ".$author->second_name,['author/select', 'id' =>$author->author_id],["class"=>"list-group-item"] );
              }   
          }
        ?>
    </div> 
</div>
<div class="col-md-8">
        <?php  foreach ($books as $book){
          $authors = "";
          $categories = "";
          foreach ($book->authors as $author){
             $authors .=" ". Html::a($author->first_name ." ". $author->second_name,['author/select', 'id' =>$author->author_id] );
          }
          foreach ($book->categories as $category){
             $categories .=" ". Html::a($category->name,['category/select', 'id' =>$category->category_id] );
          }

                    echo 
                    "<div class='col-md-6'>
                       <div class='thumbnail'>
                        ".Html::img('@web/uploads/'.$book->cover,["class" => "cover-img"] )."
                           <div class='caption'>
                               <h4><a href='#'>". $book->name."</a></h4>
                               <p> By ".$authors."</p>
                               <p> Categories: ".$categories."</p>
                           ".Html::a("Download book",'@web/uploads/'.$book->body,['data-pjax'=>0])."
                           </div>
                       </div>
                   </div>";  
      }  
      ?>   
</div>

views/site/_bookReview.php
<?php 
use yii\helpers\Html;

foreach ($books as $book){
    $authors = "";
    $categories = "";
    foreach ($book->authors as $author){
       $authors .=" ". Html::a($author->first_name ." ". $author->second_name,['author/select', 'id' =>$author->author_id] );
    }
    foreach ($book->categories as $category){
       $categories .=" ". Html::a($category->name,['category/select', 'id' =>$category->category_id] );
    }
    
 echo 
 "<div class='col-md-4'>
    <div class='thumbnail'>
     ".Html::img('@web/uploads/'.$book->cover,["class" => "cover-img"] )."
        <div class='caption'>
            <h4><a href='#'>". $book->name."</a></h4>
            <p> By ".$authors."</p>
            <p> Categories: ".$categories."</p>
        ".Html::a("Download book",'@web/uploads/'.$book->body,['data-pjax'=>0])."
        </div>
    </div>
</div>";  
}  
?>

views/site/_categoryReview.php
<?php 
use app\models\Category;
use yii\helpers\Html;

$bookCategories = Category::find()->andWhere(['>','category_id',0])->all();
?>
<div class="col-md-4">
    <div class="list-group">
        <?php
          foreach ($bookCategories as $category){
              if(isset($_GET['id'])){
                   if($category->category_id == $_GET['id']){
                        echo Html::a($category->name,['category/select', 'id' =>$category->category_id],["class"=>"list-group-item active"] );    
                   }
                   else{
                        echo Html::a($category->name,['category/select', 'id' =>$category->category_id],["class"=>"list-group-item"] );  
                   }   
              }
              else{
                  echo Html::a($category->name,['category/select', 'id' =>$category->category_id],["class"=>"list-group-item"] );  
              }
          }
        ?>
    </div> 
</div>

<div class="col-md-8">
        <?php  foreach ($books as $book){
          $authors = "";
          $categories = "";
          foreach ($book->authors as $author){
             $authors .=" ". Html::a($author->first_name ." ". $author->second_name,['author/select', 'id' =>$author->author_id] );
          }
          foreach ($book->categories as $category){
             $categories .=" ". Html::a($category->name,['category/select', 'id' =>$category->category_id] );
          }

                    echo 
                    "<div class='col-md-6'>
                       <div class='thumbnail'>
                        ".Html::img('@web/uploads/'.$book->cover,["class" => "cover-img"] )."
                           <div class='caption'>
                               <h4><a href='#'>". $book->name."</a></h4>
                               <p> By ".$authors."</p>
                               <p> Categories: ".$categories."</p>
                           ".Html::a("Download book",'@web/uploads/'.$book->body,['data-pjax'=>0])."
                           </div>
                       </div>
                   </div>";  
      }  
      ?>   
</div>

views/site/error.php
<?php
use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
use yii\widgets\LinkPager;
use yii\bootstrap\Nav;
$this->title = 'Library';
$selectedCategory;
?>
  <?php Pjax::begin(['timeout' => 5000]); ?>
<div class="site-index">
    <div class="col-md-3"> 
            <?php
            $menuItems = [];
            if($selectedCategory == "book"){
                   $menuItems[] = ['label' => 'Books', 'url' => ['/site/index'],"options" =>["class"=>"active"]];
                   $menuItems[] = ['label' => 'Categories', 'url' => ['/category/index']];
                   $menuItems[] = ['label' => 'Authors', 'url' => ['/author/index']];
            }
            else if($selectedCategory == "category"){
                   $menuItems[] = ['label' => 'Books', 'url' => ['/site/index']];
                   $menuItems[] = ['label' => 'Categories', 'url' => ['/category/index'],"options" =>["class"=>"active"]];
                   $menuItems[] = ['label' => 'Authors', 'url' => ['/author/index']];
            }
            else if($selectedCategory == "author"){
                   $menuItems[] = ['label' => 'Books', 'url' => ['/site/index']];
                   $menuItems[] = ['label' => 'Categories', 'url' => ['/category/index']];
                   $menuItems[] = ['label' => 'Authors', 'url' => ['/author/index'],"options" =>["class"=>"active"]];
            }
 
            echo Nav::widget([
            'options' => ['class' => 'nav nav-pills nav-stacked'],
            'items' => $menuItems
                ]);
             ?>

    </div> 
    
    <div class="col-md-9">      
                <?php 
                if($selectedCategory == "book"){
                    echo $this->render("_bookReview",["books" => $books]);
                }
                else if($selectedCategory == "category"){
                    echo $this->render("_categoryReview",["books" => $books]);
                }
                else if($selectedCategory == "author"){
                    echo $this->render("_authorReview",["books" => $books]);
                }
                ?>
    </div>  
</div>
 <footer class="footer">
    <div class="container text-center navbar-fixed-bottom">
          <?php   echo LinkPager::widget([
                 'pagination' => $bookPages,
            ]); 
          ?>
    </div>
</footer>
 <?php Pjax::end(); ?>

 <?php echo $this->render("//book/add",["addBookModel" => $addBookModel]); ?>
 <?php echo $this->render("//category/add",["addCategoryModel" => $addCategoryModel]);?>
 <?php echo $this->render("//author/add",["addAuthorModel" => $addAuthorModel]);

 

views/site/login.php
<?php
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
?>
<div class="container">
    <div class="col-md-offset-4 col-md-4 center-form">
        <div class="panel panel-default">
            <div class="panel-body">
              SignIn
            </div>
            <div class="panel-footer">
                 <?php Pjax::begin(['timeout' => 5000]); ?>
                 <?php $form = ActiveForm::begin([
                             'id' => 'login-form',
                             'method' => 'post',
                             'action' => ['authentication/login'],
                             'options' => ['onsubmit' => 'return false','data-pjax' => true],
                             'enableClientValidation' => true,
                              ]); ?>
            
                  <div class="form-group">
                       <?= $form->field($model, 'login')->label("Login") ?>
                  </div>
                  <div class="form-group">
                       <?= $form->field($model, 'password')->passwordInput()->label("Password") ?>
                  </div> 
                  <div class="form-group">
                       <?= $form->field($model, 'rememberMe')->checkbox() ?>
                  </div>
                  <div class="modal-footer">
                      <button type="submit" class="btn btn-primary" id="login-btn">SignIn</button>
                      <button type="reset" class="btn btn-default" data-dismiss="modal">Clear</button>
                  </div>
                 <?php ActiveForm::end(); ?>
              <?php Pjax::end(); ?>
   
            </div>
          </div>  
    </div>
</div>
            
           