models/Book.php
<?php
namespace app\models;
use yii\db\ActiveRecord;
use app\models\Author;
use app\models\Category;

class Book extends ActiveRecord {
    private $book_id;
    private $name;
    private $cover;
    private $body;

    public static function tableName(){
        return 'book';
    }
    
    public function getAuthors(){  
       return $this->hasMany(Author::className(), ['author_id' => 'author_id'])->viaTable('book_author', ['book_id' => 'book_id']);
    }
    
    public function getCategories(){  
       return $this->hasMany(Category::className(), ['category_id' => 'category_id'])->viaTable('book_category', ['book_id' => 'book_id']);
    }
    
    
}  

controllers/BookController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Book;
use yii\data\ActiveDataProvider;
use app\models\Author;
use app\models\BookFilterForm;
use app\models\NewBookForm;
use app\models\RegistrationForm;
use app\models\LoginForm;
use yii\data\Pagination;
use app\models\AddAuthorForm;
use app\models\AddCategoryForm;


class BookController extends Controller{ 
    
    public function actions(){
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    
    private $books;
    private $bookPages;
    private $addBookModel;
    private $selectedCategory;
    private $addCategoryModel;
    private $addAuthorModel;
            
    function __construct($id, $module){
        parent::__construct($id, $module);
     }
     
    public function Initialization(){
        $_SESSION["category"] = [];
        $model = Book::find()
                ->with('authors')
                ->with('categories');
        $countQuery = clone $model;
        $this->bookPages = new Pagination(['totalCount' => $countQuery->count(),'pageSize'=>3]);
        $this->books = $model->offset($this->bookPages->offset)
                 ->limit($this->bookPages->limit)
                 ->all();
        $this->addBookModel = new NewBookForm();
        $this->selectedCategory = "category";
        $this->addCategoryModel = new AddCategoryForm();
        $this->addAuthorModel = new AddAuthorForm();    
    }
    
    public function actionIndex(){
        return $this->render('//site/index',[
            "books"=>$this->books,
            "bookPages" => $this->bookPages,
            "addBookModel" => $this->addBookModel,
            "selectedCategory"=> $this->selectedCategory,
            "addCategoryModel" => $this->addCategoryModel,
            "addAuthorModel"=> $this->addAuthorModel
            ]);
    } 
     
    public function actionAddcategory(){
       $id = Yii::$app->getRequest()->getQueryParam('id');
       
    }
    
    public function actionAddauthor(){
       $id = Yii::$app->getRequest()->getQueryParam('id');
       
    }
  
}

views/book/add.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Category;
use app\models\Author;
use app\models\SelectCategory;
use yii\widgets\Pjax;
use yii\helpers\Html;

$categories = Category::find()->andWhere(['>','category_id',0])->all();
$authors = Author::find()->andWhere(['>','author_id',0])->all();
?>

<div class="modal fade" id="add-book-window">
            <div class="modal-dialog">
              <div class="modal-content">
                  <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title">Add book</h4>
                  </div>
                  <div class="modal-body">
                     <?php Pjax::begin(['timeout' => 5000]);  ?>                            
                        <?php $form = ActiveForm::begin([
                                     'id' => 'add-book-form',
                                     'method' => 'post',
                                     'action' => ['book/add'],
                                     'options' => ['enctype'=>'multipart/form-data',
                                     'onsubmit' => 'return false','data-pjax' => true],
                                     'enableClientValidation' => true,
                                      ]); ?>
                      
                          <p>Categories:  </p>  
                          <?php 
                          if (isset($session['category'])){print_r($session['category']);}
                          ?>
                          
                          
                          <p>Authors:   </p> 

                          <div class="form-group">
                               <?= $form->field($addBookModel, 'name')->label("Name") ?>
                          </div>
                          <div class="form-group">
                               <?= $form->field($addBookModel, 'cover')->fileInput(['accept' => 'image/gif,image/jpeg,image/png'])->label("Book cover") ?>
                          </div>
                           <div class="form-group">
                               <?= $form->field($addBookModel, 'body')->fileInput(['accept' => 'application/pdf,text/plain,application/msword'])->label("Book file") ?>
                          </div>

                          <?php ActiveForm::end(); ?>   
                      
                      
                          <p>Add book authors : </p>
                          <?php 
                            foreach ($authors as $author){
                              echo " /". Html::a($author->first_name ." ". $author->second_name,['book/addauthor', 'id' =>$author->author_id] );
                            }
                          ?>
                          <hr>
                          
                          <p>Add book categories : </p>
                          <?php
                            foreach ($categories as $category){
                              echo " /". Html::a($category->name,['book/addcategory', 'id' =>$category->category_id] );
                            }
                          ?>
                                         
                 <div class="modal-footer">
                     <button type="button" class="btn btn-primary" id="add-book-btn">Add</button>
                      <button type="reset" class="btn btn-default" data-dismiss="modal">Cancel</button>
                  </div>
              <?php Pjax::end(); ?>       
              </div>
           </div>
    </div> 
</div>